<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

//* Remove default loop
remove_action( 'genesis_loop', 'genesis_do_loop' );

add_action( 'genesis_loop', 'tekserve_redirect_genesis_404' );
/**
 * This function outputs a 404 "Not Found" error message
 *
 * @since 1.6
 */
 
/**
 * URL REDIRECT TEST
 *
 * urls must NOT begine with http://
 * urls must use * for wildcards in addition to setting wildcard and/or preserve_path key to true
 * this is not currently set up to with redirects based on query strings
 * the old url CANNOT contain a hash (#) as this is not available to the server
 * broadest urls must be at the end of the list! -> tekserve.com/cpus/mac/* before teksere.com/cpus/* before tekserve.com/* 
 */
$redirect_rules = array(
	
	array('old_url'       => 'www.tekserve.com/service/mac-repairs-and-upgrades', 
		  'new_url'       => 'www.tekserve.com/service/', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/service/iphone-service', 
		  'new_url'       => 'www.tekserve.com/service/#iphone', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/service/data-backup-and-recovery', 
		  'new_url'       => 'www.tekserve.com/service/#backup-recovery', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/status', 
		  'new_url'       => 'www.tekserve.com/service/#status', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/service/trade-in', 
		  'new_url'       => 'www.tekserve.com/service/#tradein-recycling', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/service/recycling', 
		  'new_url'       => 'www.tekserve.com/service/#tradein-recycling', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/service/*', 
		  'new_url'       => 'www.tekserve.com/service/', 
		  'wildcard'      => TRUE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/rentals', 
		  'new_url'       => 'rentals.tekserve.com/', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/rentals/rates', 
		  'new_url'       => 'rentals.tekserve.com/#equipment', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/rentals/equipment', 
		  'new_url'       => 'rentals.tekserve.com/#equipment', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/rentals/request-rental', 
		  'new_url'       => 'rentals.tekserve.com/#equipment', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/rentals/rental-faq', 
		  'new_url'       => 'rentals.tekserve.com/#faq', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/rentals/equipment/retina', 
		  'new_url'       => 'rentals.tekserve.com/#mbp', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/rentals/equipment/macbook-pro', 
		  'new_url'       => 'rentals.tekserve.com/#mbp', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/rentals/equipment/mac-pro', 
		  'new_url'       => 'rentals.tekserve.com/#macpro', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/rentals/equipment/ipad', 
		  'new_url'       => 'rentals.tekserve.com/#ipad', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/rentals/equipment/imac#mini', 
		  'new_url'       => 'rentals.tekserve.com/#mini', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/rentals/equipment/displays', 
		  'new_url'       => 'rentals.tekserve.com/#displays', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/rentals/equipment/projectors', 
		  'new_url'       => 'rentals.tekserve.com/#projectors', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/rentals/equipment/accessories', 
		  'new_url'       => 'rentals.tekserve.com/#accessories', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/rentals/equipment/vintage-electronics', 
		  'new_url'       => 'rentals.tekserve.com/#vintage', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/rentals/equipment/ipad#mini', 
		  'new_url'       => 'rentals.tekserve.com/#ipadmini', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/rentals/equipment/ipad#ipod', 
		  'new_url'       => 'rentals.tekserve.com/#ipodtouch', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/rentals/equipment/imac#imac', 
		  'new_url'       => 'rentals.tekserve.com/#imac', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/rentals/equipment/imac', 
		  'new_url'       => 'rentals.tekserve.com/#imac', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/blog/wp-content/uploads/2012/12/TekserveCreditCardApprovalForm.pdf', 
		  'new_url'       => 'rentals.teksserve.com/wp-content/uploads/2013/11/TekserveCreditCardApprovalForm.pdf', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/rentals/*', 
		  'new_url'       => 'rentals.tekserve.com/', 
		  'wildcard'      => TRUE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/insiders/how-to-join/', 
		  'new_url'       => 'www.tekserve.com/insider/', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/insiders/*', 
		  'new_url'       => 'www.tekserve.com/insider/', 
		  'wildcard'      => TRUE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/insider_mac/', 
		  'new_url'       => 'www.tekserve.com/insider/#mac', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/insider_ipad/', 
		  'new_url'       => 'www.tekserve.com/insider/#ipad', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/insider-members/', 
		  'new_url'       => 'www.tekserve.com/insider/', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/insider-terms-conditions/', 
		  'new_url'       => 'www.tekserve.com/insider/#terms', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/tekserve-events/', 
		  'new_url'       => 'events.tekserve.com/', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/tekserve-events/*', 
		  'new_url'       => 'events.tekserve.com/', 
		  'wildcard'      => TRUE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/events/tekserve-academy/', 
		  'new_url'       => 'events.tekserve.com/#academy', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/events/creative-fridays/', 
		  'new_url'       => 'events.tekserve.com/#creativefridays', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/events/', 
		  'new_url'       => 'events.tekserve.com/', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE ),		  
		  
	array('old_url'       => 'www.tekserve.com/events/*', 
		  'new_url'       => 'events.tekserve.com/', 
		  'wildcard'      => TRUE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/knowledge/*', 
		  'new_url'       => 'faq.tekserve.com/', 
		  'wildcard'      => TRUE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/faq-menu/', 
		  'new_url'       => 'faq.tekserve.com/', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/blog/', 
		  'new_url'       => 'blog.tekserve.com/', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/blog/*', 
		  'new_url'       => 'blog.tekserve.com/*', 
		  'wildcard'      => TRUE, 
		  'preserve_path' => TRUE 
	),	  
	array('old_url'       => 'www.tekserve.com/business/blog/', 
		  'new_url'       => 'blog.tekserve.com/', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/business/blog/*', 
		  'new_url'       => 'blog.tekserve.com/*', 
		  'wildcard'      => TRUE, 
		  'preserve_path' => TRUE 
	),	  
	array('old_url'       => 'www.tekserve.com/business/Blog/', 
		  'new_url'       => 'blog.tekserve.com/', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/business/Blog/*', 
		  'new_url'       => 'blog.tekserve.com/*', 
		  'wildcard'      => TRUE, 
		  'preserve_path' => TRUE ),
		  
		  
	array('old_url'       => 'www.tekserve.com/about/store-location-and-hours/', 
		  'new_url'       => 'www.tekserve.com/about/#hours', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/about/contact-us', 
		  'new_url'       => 'www.tekserve.com/#contact', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/about/careers/', 
		  'new_url'       => 'www.tekserve.com/about/#careers', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/about/social-responsibility/', 
		  'new_url'       => 'www.tekserve.com/about/#responsibility', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/about/press/', 
		  'new_url'       => 'www.tekserve.com/about/#mentions', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/about/media-resources/', 
		  'new_url'       => 'www.tekserve.com/about/#forpress', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/about/history/', 
		  'new_url'       => 'www.tekserve.com/about/', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/about/*', 
		  'new_url'       => 'www.tekserve.com/about/', 
		  'wildcard'      => TRUE, 
		  'preserve_path' => FALSE ),		  
		  
	array('old_url'       => 'www.tekserve.com/business/products/', 
		  'new_url'       => 'www.tekserve.com/business/#partners', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/business/products/*', 
		  'new_url'       => 'www.tekserve.com/business/#partners', 
		  'wildcard'      => TRUE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/business-case-studies/', 
		  'new_url'       => 'www.tekserve.com/business/', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/business/case-studies/', 
		  'new_url'       => 'www.tekserve.com/business/', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/business/case-studies/*', 
		  'new_url'       => 'www.tekserve.com/business/', 
		  'wildcard'      => TRUE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/business-knowledge/', 
		  'new_url'       => 'www.tekserve.com/business/', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/business-knowledge/*', 
		  'new_url'       => 'www.tekserve.com/business/', 
		  'wildcard'      => TRUE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/business-contact-us/', 
		  'new_url'       => 'www.tekserve.com/business/#contact', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/business/Contact-Us/', 
		  'new_url'       => 'www.tekserve.com/business/#contact', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/business/iPad-and-iPhone-Integration/', 
		  'new_url'       => 'www.tekserve.com/business/#ios', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/business/iPad-and-iPhone-Integration/*', 
		  'new_url'       => 'www.tekserve.com/business/#ios', 
		  'wildcard'      => TRUE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/business/events/*', 
		  'new_url'       => 'events.tekserve.com/', 
		  'wildcard'      => TRUE, 
		  'preserve_path' => FALSE ),

	array('old_url'       => 'www.tekserve.com/business-events/', 
		  'new_url'       => 'events.tekserve.com/', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/business-events/*', 
		  'new_url'       => 'events.tekserve.com/', 
		  'wildcard'      => TRUE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/business/Managed-IT-Solutions/*', 
		  'new_url'       => 'www.tekserve.com/business/#services', 
		  'wildcard'      => TRUE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/business/Managed-IT-Solutions/', 
		  'new_url'       => 'www.tekserve.com/business/#services', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE ),		  
		  
	array('old_url'       => 'www.tekserve.com/business/Professional-Audio/', 
		  'new_url'       => 'www.tekserve.com/business/#creative', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE ),

	array('old_url'       => 'www.tekserve.com/business/Professional-Audio/*', 
		  'new_url'       => 'www.tekserve.com/business/#creative', 
		  'wildcard'      => TRUE, 
		  'preserve_path' => FALSE ),

	array('old_url'       => 'www.tekserve.com/business/Professional-Video/', 
		  'new_url'       => 'www.tekserve.com/business/#creative', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/business/Professional-Video/*', 
		  'new_url'       => 'www.tekserve.com/business/#creative', 
		  'wildcard'      => TRUE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/business/Digital-Publishing/*', 
		  'new_url'       => 'www.tekserve.com/business/#creative', 
		  'wildcard'      => TRUE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/business/Digital-Publishing/', 
		  'new_url'       => 'www.tekserve.com/business/#creative', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/business/Customized-Training/', 
		  'new_url'       => 'www.tekserve.com/business/#services', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/business/Customized-Training/*', 
		  'new_url'       => 'www.tekserve.com/business/#services', 
		  'wildcard'      => TRUE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/business/Data-Storage-and-Security/', 
		  'new_url'       => 'www.tekserve.com/business/#fulfillment', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/business/Data-Storage-and-Security/*', 
		  'new_url'       => 'www.tekserve.com/business/#fulfillment', 
		  'wildcard'      => TRUE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/business/Press/', 
		  'new_url'       => 'www.tekserve.com/about/#mentions', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/business/Press/*', 
		  'new_url'       => 'www.tekserve.com/about/#mentions', 
		  'wildcard'      => TRUE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/business/hours-and-location/', 
		  'new_url'       => 'www.tekserve.com/about/#hours', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/business/careers/', 
		  'new_url'       => 'www.tekserve.com/about/#careers', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/business/about/management-team/', 
		  'new_url'       => 'www.tekserve.com/about/', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/business/about/social-responsibility/', 
		  'new_url'       => 'www.tekserve.com/about/#responsibility', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/business/press-resources/', 
		  'new_url'       => 'www.tekserve.com/about/#forpress', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/business/about/history/', 
		  'new_url'       => 'www.tekserve.com/about/', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/business/Mac-Service/', 
		  'new_url'       => 'www.tekserve.com/service/', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/business/rentals-and-leasing', 
		  'new_url'       => 'rentals.tekserve.com/#leasing', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/business/newsletter', 
		  'new_url'       => 'www.tekserve.com/#footer', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE ),

	array('old_url'       => 'www.tekserve.com/business/*', 
		  'new_url'       => 'www.tekserve.com/business/', 
		  'wildcard'      => TRUE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/youtube', 
		  'new_url'       => 'www.youtube.com/tekserve', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/teknews/', 
		  'new_url'       => 'www.tekserve.com/#footer', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/twitter', 
		  'new_url'       => 'www.twitter.com/tekserve', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/training', 
		  'new_url'       => 'www.tekserve.com/business/#services', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/tradein', 
		  'new_url'       => 'www.tekserve.com/service/#tradein-recycling', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/tekserve-insiders/', 
		  'new_url'       => 'www.tekserve.com/insider/', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/tekserve-business-site/', 
		  'new_url'       => 'www.tekserve.com/business/', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/store/weborderfaq.php', 
		  'new_url'       => 'www.tekserve.com/policies/#order-return', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/ordering-returns/', 
		  'new_url'       => 'www.tekserve.com/policies/#order-return', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/store/trade-in.php', 
		  'new_url'       => 'www.tekserve.com/service/#tradein-recycling', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/status/index.php', 
		  'new_url'       => 'www.tekserve.com/service/#status', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/business-solutions/', 
		  'new_url'       => 'www.tekserve.com/business/', 
		  'wildcard'      => FALSE, 
		  'preserve_path' => FALSE 
	),	  
	array('old_url'       => 'www.tekserve.com/*', 
		  'new_url'       => 'store.tekserve.com/*', 
		  'wildcard'      => TRUE, 
		  'preserve_path' => TRUE 
	),	  		  
);

/**
 * get_redirect_url
 *
 * returned array from parse_url -> http://php.net/manual/en/function.parse-url.php
 * 	array(4) {
 * 		["scheme"]=>
 *			string(4) "http"
 *		["host"]=>
 *			string(16) "www.tekserve.com"
 * 		["path"]=>
 *			string(16) "/store/index.php"
 * 		["query"]=>
 * 			string(10) "w=whatever"
 * 	}
 *
 * get url
 * compare against rule
 * if url is wildcard
 * 		check that rule old_url matches beginging of url
 * else	
 * 		check for complete match
 * if rule equires peserving path, then append the rest of the path information
 */
function get_redirect_url( $url, $redirect_rules )
{
	// get parts for current path
	$url_parts = parse_url($url);
	// clean url
	$input_url = $url_parts['host'].@$url_parts['path'];
	// add trailing slash if none exists
	if( substr($input_url, -1) !== '/' ) $input_url .= '/';
	
	$i = 1;
	// loop thru rules, on match, exit function with return
	foreach( $redirect_rules as $rule )
	{
		// if wildcard or preserve path, trim asterisk from url
		if( $rule['wildcard']      ){ $rule['old_url'] = trim( $rule['old_url'], '*' ); }
		if( $rule['preserve_path'] ){ $rule['new_url'] = trim( $rule['new_url'], '*' ); }
		
		// get parts for rule old url. we have to add a scheme or parse_url() to work properly
		$compare_url_parts = parse_url('http://'.$rule['old_url']);
		// clean compare url
		$compare_url = $compare_url_parts['host'].@$compare_url_parts['path'];
		// add trailing slash if none exists
		if( substr($compare_url, -1) !== '/' ) $compare_url .= '/';		
		
		$is_match = FALSE;
		if($rule['wildcard']){
			if( substr( $input_url, 0, strlen($compare_url)) === $compare_url ) $is_match = TRUE;
		}else{
			if( $input_url === $compare_url ) $is_match = TRUE;
		}
		
//		DEBUGGING			
// 		echo $i.' '.( $is_match ? '<b>TRUE</b>' : '' ).'<br />'; $i++;
// 		echo ( $rule['wildcard'] ? 'W: '.substr( $input_url, 0, strlen($compare_url)) : 'STATIC' ).' '.( $rule['preserve_path'] ? 'PRESERVE PATH' : '' ).'<br />';
// 		echo "\t<b>".$compare_url.'</b><br />'; 		
// 		echo "\t".$input_url.'<br />';
// 		echo "\t".$rule['new_url'].'<br />';
		
		if($is_match){
			$redirect_to = $rule['new_url'];
			// append path rest of path info if required
			if($rule['preserve_path']){
				$redirect_to = str_replace( $rule['old_url'], $rule['new_url'], $url);
			}
			// return the new path
			return $url_parts['scheme'].$redirect_to;
		}
	}
	// if we went through all rules with no match, return 404
	return '404';
}

 
 


/**
 * TESTS
 * static (no wildcard), without trailing slash -> www.tekserve.com/business/rentals-and-leasing
 * static (no wildcard), with trailing slash -> www.tekserve.com/business/rentals-and-leasing/
 * wildcard, no preserve path with no extra characters, without trailing slash -> http://www.tekserve.com/business/Digital-Publishing
 * wildcard, no preserve path with no extra characters, with trailing slash -> http://www.tekserve.com/business/Digital-Publishing/
 * wildcard, no preserve path with extra characters, without trailing slash -> http://www.tekserve.com/business/Digital-Publishing/blahblahblah
 * wildcard, no preserve path with extra characters, with trailing slash -> http://www.tekserve.com/business/Digital-Publishing/blahblahblah/ 
 * wildcard, preserve path, without trailing slash -> http://www.tekserve.com/testthisout
 * wildcard, preserve path, with trailing slash -> http://www.tekserve.com/testthisout/
 */ 
 
 
function tekserve_redirect_genesis_404() {


$url = urldecode(@$_REQUEST['url']);

// var_dump($_REQUEST['url']);
// var_dump(parse_url($_SERVER['SCRIPT_URI'].'?'.$_SERVER['QUERY_STRING']));
// array( array( (string) old_url, (string) new_url, (bool) wildcard, (bool) preserve_path )

$redirect_to = get_redirect_url( $url, $redirect_rules );
echo 'REDIRECT TO: '.$redirect_to;
	/* here */

	echo genesis_html5() ? '<article class="entry">' : '<div class="post hentry">';

		printf( '<h1 class="entry-title">%s</h1>', __( 'Not found, error 404', 'genesis' ) );
		echo '<div class="entry-content">';

			if ( genesis_html5() ) :

				echo '<p>' . sprintf( __( 'The page you are looking for no longer exists. Perhaps you can return back to the site\'s <a href="%s">homepage</a> and see if you can find what you are looking for. Or, you can try finding it by using the search form below.', 'genesis' ), home_url() ) . '</p>';

				echo '<p>' . get_search_form() . '</p>';

			else :
	?>

			<p><?php printf( __( 'The page you are looking for no longer exists. Perhaps you can return back to the site\'s <a href="%s">homepage</a> and see if you can find what you are looking for. Or, you can try finding it with the information below.', 'genesis' ), home_url() ); ?></p>

			<h4><?php _e( 'Pages:', 'genesis' ); ?></h4>
			<ul>
				<?php wp_list_pages( 'title_li=' ); ?>
			</ul>

			<h4><?php _e( 'Categories:', 'genesis' ); ?></h4>
			<ul>
				<?php wp_list_categories( 'sort_column=name&title_li=' ); ?>
			</ul>

			<h4><?php _e( 'Authors:', 'genesis' ); ?></h4>
			<ul>
				<?php wp_list_authors( 'exclude_admin=0&optioncount=1' ); ?>
			</ul>

			<h4><?php _e( 'Monthly:', 'genesis' ); ?></h4>
			<ul>
				<?php wp_get_archives( 'type=monthly' ); ?>
			</ul>

			<h4><?php _e( 'Recent Posts:', 'genesis' ); ?></h4>
			<ul>
				<?php wp_get_archives( 'type=postbypost&limit=100' ); ?>
			</ul>

<?php
			endif;

			echo '</div>';

		echo genesis_html5() ? '</article>' : '</div>';

}

genesis();
